; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Ink Canvas Plus"
; #define MyAppVersion "4.0.0.4"
#define MyAppPublisher "Clover Yan"
#define MyAppURL "https://cloveryan.com/apps/Ink-Canvas-Plus"
#define MyAppExeName "Ink Canvas.exe"
#define MyAppAssocName MyAppName + " Strokes"
#define MyAppAssocExt ".icstk"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
#define MyAppVersion GetVersionNumbersString("..\Ink Canvas\bin\Release\Ink Canvas.exe")

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4A20B75F-FFBE-4CD7-8A77-24BC4926241A}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppComments={#MyAppName}
AppCopyright=Copyright © {#MyAppPublisher}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppPublisher}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ChangesAssociations=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
InfoBeforeFile="infobefore.txt"
LicenseFile=..\LICENSE
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputDir="output"
OutputBaseFilename=Ink-Canvas-Plus_setup_{#MyAppVersion}
SetupIconFile=..\Ink Canvas\Resources\InkCanvas.ico
SolidCompression=yes
WizardStyle=modern
DisableWelcomePage=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
Name: "runonstartup"; Description: "开机时运行 {#MyAppName} (&R)"; GroupDescription: "自动启动："; Flags: checkedonce
Name: "migratesettings"; Description: "设置 (&S)"; GroupDescription: "从 WXRIW 版 Ink Canvas 迁移（如有）："; Flags: checkedonce unchecked
Name: "migratenames"; Description: "抽奖名单 (&L)"; GroupDescription: "从 WXRIW 版 Ink Canvas 迁移（如有）："; Flags: checkedonce

[Files]
Source: "..\Ink Canvas\bin\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\AutoUpdater.NET.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\IACore.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\IALoader.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\IAWinFX.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\Ink Canvas.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\Ink Canvas.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\Ink Canvas.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\iNKORE.UI.WPF.Modern.Controls.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\iNKORE.UI.WPF.Modern.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\Microsoft.Office.Interop.PowerPoint.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\Microsoft.Web.WebView2.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\Microsoft.Web.WebView2.WinForms.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\Microsoft.Web.WebView2.Wpf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\Office.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\System.ValueTuple.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\WebView2Loader.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\Windows.Foundation.UniversalApiContract.winmd"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Ink Canvas\bin\Release\zh\*"; DestDir: "{app}\zh"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userstartup}\InkCanvas"; Filename: "{app}\{#MyAppExeName}"; Tasks: runonstartup

[Run]
Filename: "{sys}\taskkill.exe"; Description: "Terminate {#MyAppName}"; Parameters: "/IM ""{#MyAppExeName}"" /F"; Flags: runhidden
Filename: "{sys}\cmd.exe"; Description: "Migrate Settings.json"; Parameters: "/C ""COPY /Y ""{userappdata}\WXRIW\Ink Canvas\Settings.json"" ""{app}"""""; Flags: runhidden; Tasks: migratesettings
Filename: "{sys}\cmd.exe"; Description: "Migrate Names.txt"; Parameters: "/C ""COPY /Y ""{userappdata}\WXRIW\Ink Canvas\Names.txt"" ""{app}"""""; Flags: runhidden; Tasks: migratenames
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall

[InstallDelete]
Type: files; Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}.url"

[UninstallDelete]
Type: files; Name: "{app}\Log.txt"
Type: files; Name: "{app}\Versions.ini"
Type: files; Name: "{app}\Settings.json"
Type: dirifempty; Name: "{app}"
Type: files; Name: "{userstartup}\InkCanvas.lnk"

[UninstallRun]
Filename: "{sys}\taskkill.exe"; Parameters: "/IM ""{#MyAppExeName}"" /F"; RunOnceId: "KillInkCanvasPlus"; Flags: runhidden

[Messages]
BeveledLabel=https://cloveryan.com/ic+ {#MyAppVersion}

[Code]
procedure InitializeWizard();
begin
  WizardForm.LicenseAcceptedRadio.Checked := True;
end;